"""
generate_init.py
Generates init.sql (Microsoft SQL Server 2022) with:
  - 500 companies (3-level hierarchy: 25 root, 100 level-1, 375 level-2)
  - 15 users with reporting hierarchy
  - 5 000 transactions spread across all 500 companies and 15 users
Run: python generate_init.py
Output: init.sql (overwrites existing)
Target: mcr.microsoft.com/mssql/server:2022-latest Linux image.
        Script runs as SA against the CompanyData database.
"""
import random, datetime, os

random.seed(42)

industries = [
    "Technology","Finance","Healthcare","Retail","Manufacturing",
    "Logistics","Energy","Education","Media","Real Estate",
    "Construction","Hospitality","Agriculture","Automotive","Consulting"
]
adj = ["Global","Premier","Advanced","Dynamic","Integrated","Strategic","Unified",
       "Allied","Summit","Apex","Pinnacle","Horizon","Nexus","Vertex","Catalyst",
       "Elite","Optimal","Quantum","Vanguard","Sovereign"]
nouns = ["Solutions","Group","Industries","Holdings","Partners","Ventures","Systems",
         "Networks","Technologies","Enterprises","Capital","Services","Dynamics",
         "Resources","Innovations","Consulting","Associates","Worldwide","Connect","Plus"]
suffixes = ["Inc.","LLC","Ltd.","Corp.","Co.","Group","SA","GmbH","plc","AG"]

# 500 unique company names
names, seen = [], set()
for a in adj:
    for n in nouns:
        for s in suffixes:
            nm = f"{a} {n} {s}"
            if nm not in seen and len(names) < 500:
                seen.add(nm); names.append(nm)

# company_id ranges
roots  = list(range(1, 26))
level1 = list(range(26, 126))
level2 = list(range(126, 501))

rows_co = []
for i in range(25):
    yr = random.randint(1975, 2000)
    rows_co.append((names[i], "NULL", 0, random.choice(industries),
                    f"{yr}-{random.randint(1,12):02d}-01"))
for i in range(100):
    parent = roots[i // 4]
    yr = random.randint(1990, 2010)
    rows_co.append((names[25+i], str(parent), 1, random.choice(industries),
                    f"{yr}-{random.randint(1,12):02d}-01"))
for i in range(375):
    parent = random.choice(level1)
    yr = random.randint(2000, 2022)
    rows_co.append((names[125+i], str(parent), 2, random.choice(industries),
                    f"{yr}-{random.randint(1,12):02d}-01"))

dept_names = ["Executive","Engineering","Sales","Finance","Operations",
              "Marketing","HR","Legal","IT","Product"]
first_names = ["Alice","Bob","Carlos","Diana","Ethan","Fatima","George",
               "Hana","Ivan","Julia","Kevin","Laura","Marcus","Nina","Oscar"]
last_names  = ["Smith","Johnson","Williams","Brown","Jones","Garcia","Miller",
               "Davis","Wilson","Martinez","Anderson","Taylor","Thomas","Moore","Jackson"]
titles = ["CEO","VP Engineering","Senior Developer","Sales Director",
          "Account Executive","Finance Manager","Data Analyst","Marketing Manager",
          "HR Director","Operations Manager","Product Manager","Legal Counsel",
          "IT Manager","Developer","Consultant"]

mgr_map = {1: "NULL"}
for uid in range(2, 6):  mgr_map[uid] = "1"
for uid in range(6, 16): mgr_map[uid] = str(random.randint(2, 5))

all_cids = list(range(1, 501))
base_date = datetime.date(2023, 1, 1)
date_range_days = (datetime.date(2025, 12, 31) - base_date).days
statuses = (["Completed"] * 80) + (["Pending"] * 10) + (["Failed"] * 6) + (["Refunded"] * 4)
type_descs = {1:"Purchase",2:"Refund",3:"Credit",4:"Subscription",5:"Fee",6:"Adjustment"}

out = []

def w(*args):
    out.extend(args)

# ── header ────────────────────────────────────────────────────────────────────
w(
    "-- ==============================================================================",
    "-- init.sql  --  CompanyData schema (Microsoft SQL Server 2022)",
    "--              500 companies (hierarchy), 15 users, 5 000 transactions",
    "-- Auto-generated by generate_init.py -- DO NOT EDIT BY HAND",
    "-- Runs as SA against the CompanyData database",
    "-- ==============================================================================",
    "",
)

# ── schema ────────────────────────────────────────────────────────────────────
w(
    "-- Companies",
    "CREATE TABLE Companies (",
    "    company_id        INT            IDENTITY(1,1) NOT NULL,",
    "    company_name      NVARCHAR(200)  NOT NULL,",
    "    parent_company_id INT            NULL,",
    "    company_level     SMALLINT       DEFAULT 0 NOT NULL,",
    "    industry          NVARCHAR(100)  NULL,",
    "    founded_date      DATE           NULL,",
    "    is_active         BIT            DEFAULT 1 NOT NULL,",
    "    created_at        DATETIME2      DEFAULT GETDATE() NOT NULL,",
    "    CONSTRAINT PK_Companies        PRIMARY KEY (company_id),",
    "    CONSTRAINT FK_Companies_Parent FOREIGN KEY (parent_company_id)",
    "        REFERENCES Companies (company_id)",
    ");",
    "CREATE INDEX IX_Companies_Parent ON Companies (parent_company_id);",
    "GO",
    "",
    "-- Departments",
    "CREATE TABLE Departments (",
    "    department_id        INT            IDENTITY(1,1) NOT NULL,",
    "    department_name      NVARCHAR(200)  NOT NULL,",
    "    company_id           INT            NOT NULL,",
    "    parent_department_id INT            NULL,",
    "    is_active            BIT            DEFAULT 1 NOT NULL,",
    "    created_at           DATETIME2      DEFAULT GETDATE() NOT NULL,",
    "    CONSTRAINT PK_Departments        PRIMARY KEY (department_id),",
    "    CONSTRAINT FK_Departments_Company FOREIGN KEY (company_id)",
    "        REFERENCES Companies (company_id),",
    "    CONSTRAINT FK_Departments_Parent  FOREIGN KEY (parent_department_id)",
    "        REFERENCES Departments (department_id)",
    ");",
    "CREATE INDEX IX_Departments_Company ON Departments (company_id);",
    "GO",
    "",
    "-- Users",
    "CREATE TABLE Users (",
    "    user_id       INT            IDENTITY(1,1) NOT NULL,",
    "    username      NVARCHAR(100)  NOT NULL,",
    "    email         NVARCHAR(255)  NOT NULL,",
    "    first_name    NVARCHAR(100)  NOT NULL,",
    "    last_name     NVARCHAR(100)  NOT NULL,",
    "    company_id    INT            NOT NULL,",
    "    department_id INT            NULL,",
    "    manager_id    INT            NULL,",
    "    job_title     NVARCHAR(200)  NULL,",
    "    hire_date     DATE           NULL,",
    "    is_active     BIT            DEFAULT 1 NOT NULL,",
    "    created_at    DATETIME2      DEFAULT GETDATE() NOT NULL,",
    "    CONSTRAINT PK_Users         PRIMARY KEY (user_id),",
    "    CONSTRAINT UQ_Username      UNIQUE      (username),",
    "    CONSTRAINT UQ_Email         UNIQUE      (email),",
    "    CONSTRAINT FK_Users_Company FOREIGN KEY (company_id)",
    "        REFERENCES Companies (company_id),",
    "    CONSTRAINT FK_Users_Dept    FOREIGN KEY (department_id)",
    "        REFERENCES Departments (department_id),",
    "    CONSTRAINT FK_Users_Manager FOREIGN KEY (manager_id)",
    "        REFERENCES Users (user_id)",
    ");",
    "CREATE INDEX IX_Users_Company ON Users (company_id);",
    "CREATE INDEX IX_Users_Manager ON Users (manager_id);",
    "GO",
    "",
    "-- Transaction Types",
    "CREATE TABLE TransactionTypes (",
    "    type_id     INT            IDENTITY(1,1) NOT NULL,",
    "    type_name   NVARCHAR(50)   NOT NULL,",
    "    description NVARCHAR(200)  NULL,",
    "    CONSTRAINT PK_TransactionTypes PRIMARY KEY (type_id),",
    "    CONSTRAINT UQ_TransactionType  UNIQUE      (type_name)",
    ");",
    "GO",
    "",
    "-- Transactions",
    "CREATE TABLE Transactions (",
    "    transaction_id   INT            IDENTITY(1,1) NOT NULL,",
    "    user_id          INT            NOT NULL,",
    "    company_id       INT            NOT NULL,",
    "    transaction_date DATETIME2      NOT NULL,",
    "    amount           DECIMAL(18,2)  NOT NULL,",
    "    type_id          INT            NOT NULL,",
    "    description      NVARCHAR(500)  NULL,",
    "    reference_number NVARCHAR(100)  NULL,",
    "    status           NVARCHAR(20)   DEFAULT N'Completed' NOT NULL,",
    "    created_at       DATETIME2      DEFAULT GETDATE() NOT NULL,",
    "    CONSTRAINT PK_Transactions  PRIMARY KEY (transaction_id),",
    "    CONSTRAINT FK_Txn_User      FOREIGN KEY (user_id)     REFERENCES Users            (user_id),",
    "    CONSTRAINT FK_Txn_Company   FOREIGN KEY (company_id)  REFERENCES Companies        (company_id),",
    "    CONSTRAINT FK_Txn_Type      FOREIGN KEY (type_id)     REFERENCES TransactionTypes (type_id),",
    "    CONSTRAINT CK_Txn_Status    CHECK (status IN (N'Pending',N'Completed',N'Failed',N'Refunded'))",
    ");",
    "CREATE INDEX IX_Txn_User    ON Transactions (user_id);",
    "CREATE INDEX IX_Txn_Company ON Transactions (company_id);",
    "CREATE INDEX IX_Txn_Date    ON Transactions (transaction_date);",
    "CREATE INDEX IX_Txn_Type    ON Transactions (type_id);",
    "CREATE INDEX IX_Txn_Status  ON Transactions (status);",
    "GO",
    "",
)

# ── views ─────────────────────────────────────────────────────────────────────
w(
    "CREATE VIEW vw_CompanyHierarchy AS",
    "WITH Hierarchy (company_id, company_name, parent_company_id, company_level, hierarchy_path) AS (",
    "    SELECT company_id, company_name, parent_company_id, company_level,",
    "           CAST(company_name AS NVARCHAR(2000))",
    "    FROM Companies WHERE parent_company_id IS NULL",
    "    UNION ALL",
    "    SELECT c.company_id, c.company_name, c.parent_company_id, c.company_level,",
    "           CAST(h.hierarchy_path + N' > ' + c.company_name AS NVARCHAR(2000))",
    "    FROM Companies c",
    "    INNER JOIN Hierarchy h ON c.parent_company_id = h.company_id",
    ")",
    "SELECT * FROM Hierarchy;",
    "GO",
    "",
    "CREATE VIEW vw_UserOrgContext AS",
    "SELECT",
    "    u.user_id, u.username,",
    "    u.first_name + N' ' + u.last_name AS full_name,",
    "    u.email, u.job_title, u.hire_date, u.is_active,",
    "    c.company_name, c.industry,",
    "    d.department_name,",
    "    m.first_name + N' ' + m.last_name AS manager_name",
    "FROM Users u",
    "JOIN      Companies   c ON u.company_id    = c.company_id",
    "LEFT JOIN Departments d ON u.department_id = d.department_id",
    "LEFT JOIN Users       m ON u.manager_id    = m.user_id;",
    "GO",
    "",
)

# ── DATA ──────────────────────────────────────────────────────────────────────
w(
    "-- ==============================================================================",
    "-- DATA",
    "-- ==============================================================================",
)

# ── companies ─────────────────────────────────────────────────────────────────
# Insert in order: roots (no parent), then level1 (refs roots), then level2 (refs level1).
# Batch size 100 to stay well under the 1000-row VALUES limit.
# IDENTITY_INSERT is not needed since we let SQL Server auto-assign IDs in order.
# The generator produces rows in the same order (roots 1-25, level1 26-125, level2 126-500).
batch = []
for (nm, par, lvl, ind, fd) in rows_co:
    nm2  = nm.replace("'", "''")
    ind2 = ind.replace("'", "''")
    pval = "NULL" if par == "NULL" else par
    batch.append(f"    (N'{nm2}', {pval}, {lvl}, N'{ind2}', '{fd}')")
    if len(batch) == 100:
        w("INSERT INTO Companies (company_name, parent_company_id, company_level, industry, founded_date) VALUES")
        w(",\n".join(batch) + ";")
        batch = []
if batch:
    w("INSERT INTO Companies (company_name, parent_company_id, company_level, industry, founded_date) VALUES")
    w(",\n".join(batch) + ";")
w("GO", "")

# ── departments ───────────────────────────────────────────────────────────────
dbatch = []
for cid in roots:
    for dn in dept_names:
        dbatch.append(f"    (N'{dn}', {cid}, NULL)")
w("INSERT INTO Departments (department_name, company_id, parent_department_id) VALUES")
w(",\n".join(dbatch) + ";")
w("GO", "")

# ── users ─────────────────────────────────────────────────────────────────────
ubatch = []
for i, uid in enumerate(range(1, 16)):
    fn = first_names[i]; ln = last_names[i]
    uname = f"{fn.lower()}.{ln.lower()}"
    email = f"{fn.lower()}.{ln.lower()}@companydata.internal"
    cid   = roots[i % len(roots)]
    dept_id = (cid - 1) * 10 + (i % 10) + 1
    mgr   = mgr_map[uid]
    title = titles[i]
    yr    = random.randint(2005, 2022)
    hd    = f"{yr}-{random.randint(1,12):02d}-{random.randint(1,28):02d}"
    pval  = "NULL" if mgr == "NULL" else mgr
    ubatch.append(
        f"    (N'{uname}', N'{email}', N'{fn}', N'{ln}', "
        f"{cid}, {dept_id}, {pval}, N'{title}', '{hd}')"
    )
w("INSERT INTO Users (username, email, first_name, last_name, company_id, department_id, manager_id, job_title, hire_date) VALUES")
w(",\n".join(ubatch) + ";")
w("GO", "")

# ── transaction types ─────────────────────────────────────────────────────────
w(
    "INSERT INTO TransactionTypes (type_name, description) VALUES",
    "    (N'Purchase',     N'Product or service purchase'),",
    "    (N'Refund',       N'Returned purchase refund'),",
    "    (N'Credit',       N'Account credit applied'),",
    "    (N'Subscription', N'Recurring subscription payment'),",
    "    (N'Fee',          N'Service or processing fee'),",
    "    (N'Adjustment',   N'Manual account adjustment');",
    "GO",
    "",
)

# ── 5 000 transactions ────────────────────────────────────────────────────────
tbatch = []
for t in range(1, 5001):
    uid     = random.randint(1, 15)
    cid     = random.choice(all_cids)
    days_off= random.randint(0, date_range_days)
    txn_dt  = base_date + datetime.timedelta(days=days_off)
    hr      = random.randint(7, 18)
    mn      = random.randint(0, 59)
    dt_str  = f"{txn_dt.isoformat()} {hr:02d}:{mn:02d}:00"
    type_id = random.choices([1,2,3,4,5,6], weights=[45,10,8,20,10,7])[0]
    if   type_id == 2: amt = -round(random.uniform(50, 5000), 2)
    elif type_id == 3: amt =  round(random.uniform(10, 500), 2)
    elif type_id == 5: amt =  round(random.uniform(5, 250), 2)
    elif type_id == 6: amt =  round(random.uniform(-1000, 1000), 2)
    elif type_id == 4: amt =  float(random.choice([99,199,299,499,999,1499,1999,4999]))
    else:              amt =  round(random.uniform(100, 50000), 2)
    status  = random.choice(statuses)
    ref     = f"TXN-{t:05d}"
    desc    = type_descs[type_id]
    tbatch.append(
        f"    ({uid}, {cid}, '{dt_str}', {amt}, {type_id}, N'{desc}', N'{ref}', N'{status}')"
    )
    if len(tbatch) == 500:
        w("INSERT INTO Transactions (user_id, company_id, transaction_date, amount, type_id, description, reference_number, status) VALUES")
        w(",\n".join(tbatch) + ";")
        w("GO")
        tbatch = []
if tbatch:
    w("INSERT INTO Transactions (user_id, company_id, transaction_date, amount, type_id, description, reference_number, status) VALUES")
    w(",\n".join(tbatch) + ";")
    w("GO")

w("", "-- CompanyData initialization finished.")

# ── write file ────────────────────────────────────────────────────────────────
out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "init.sql")
with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(out))
print(f"Written {len(out)} lines  ->  {out_path}")
